import type { BrushId, BrushPreset } from '@/types'

export const BRUSHES: Record<BrushId, BrushPreset> = {
  ink: {
    id: 'ink',
    name: 'Tinta',
    size: 8,
    opacity: 1,
    hardness: 0.92,
    spacing: 0.08,
    flow: 1,
    pressureSize: true,
    pressureOpacity: false,
  },
  pencil: {
    id: 'pencil',
    name: 'Lápis',
    size: 4,
    opacity: 0.75,
    hardness: 0.55,
    spacing: 0.12,
    flow: 0.7,
    pressureSize: true,
    pressureOpacity: true,
  },
  soft: {
    id: 'soft',
    name: 'Suave',
    size: 36,
    opacity: 0.35,
    hardness: 0.15,
    spacing: 0.18,
    flow: 0.45,
    pressureSize: true,
    pressureOpacity: true,
  },
  airbrush: {
    id: 'airbrush',
    name: 'Aerógrafo',
    size: 64,
    opacity: 0.2,
    hardness: 0.05,
    spacing: 0.2,
    flow: 0.3,
    pressureSize: true,
    pressureOpacity: true,
  },
  marker: {
    id: 'marker',
    name: 'Marcador',
    size: 22,
    opacity: 0.85,
    hardness: 0.8,
    spacing: 0.1,
    flow: 0.9,
    pressureSize: false,
    pressureOpacity: false,
  },
  watercolor: {
    id: 'watercolor',
    name: 'Aquarela',
    size: 48,
    opacity: 0.28,
    hardness: 0.2,
    spacing: 0.22,
    flow: 0.4,
    pressureSize: true,
    pressureOpacity: true,
  },
  charcoal: {
    id: 'charcoal',
    name: 'Carvão',
    size: 18,
    opacity: 0.7,
    hardness: 0.35,
    spacing: 0.14,
    flow: 0.65,
    pressureSize: true,
    pressureOpacity: true,
  },
  pixel: {
    id: 'pixel',
    name: 'Pixel',
    size: 6,
    opacity: 1,
    hardness: 1,
    spacing: 0.05,
    flow: 1,
    pressureSize: false,
    pressureOpacity: false,
  },
}

export const BRUSH_LIST = Object.values(BRUSHES)

export const DEFAULT_PALETTE = [
  '#000000',
  '#FFFFFF',
  '#F2EEE6',
  '#FF6B3D',
  '#FF8F66',
  '#F4C95F',
  '#3DDC97',
  '#5BA8FF',
  '#7B6CFF',
  '#E85D75',
  '#8B5A2B',
  '#4A5568',
]
