export const BRAND = {
  name: 'CBX',
  slogan: 'O Marketplace de Capão Bonito',
  city: 'Capão Bonito',
  state: 'SP',
  whatsapp: '5515999999999',
  email: 'contato@cbx.local',
  tagline: 'Compre e venda perto de você',
} as const

export const ROUTES = {
  splash: '/splash',
  onboarding: '/onboarding',
  login: '/login',
  cadastro: '/cadastro',
  esqueciSenha: '/esqueci-senha',
  home: '/',
  categorias: '/categorias',
  categoria: (slug: string) => `/categorias/${slug}`,
  busca: '/busca',
  resultados: '/resultados',
  filtros: '/filtros',
  produto: (id: string) => `/produto/${id}`,
  vendedor: (id: string) => `/vendedor/${id}`,
  chat: '/chat',
  conversa: (id: string) => `/chat/${id}`,
  favoritos: '/favoritos',
  notificacoes: '/notificacoes',
  publicar: '/publicar',
  meusAnuncios: '/meus-anuncios',
  editarAnuncio: (id: string) => `/meus-anuncios/${id}`,
  estatisticas: (id: string) => `/meus-anuncios/${id}/estatisticas`,
  impulsionar: (id: string) => `/meus-anuncios/${id}/impulsionar`,
  planos: '/planos',
  pagarPlano: (planId: string) => `/planos/pagar?plan=${planId}`,
  lojas: '/lojas',
  loja: (id: string) => `/lojas/${id}`,
  empresas: '/empresas',
  perfil: '/perfil',
  editarPerfil: '/perfil/editar',
  enderecos: '/perfil/enderecos',
  historico: '/perfil/historico',
  compras: '/perfil/compras',
  configuracoes: '/configuracoes',
  ajuda: '/ajuda',
  suporte: '/suporte',
  sobre: '/sobre',
  privacidade: '/privacidade',
  termos: '/termos',
  offline: '/offline',
  erro: '/erro',
} as const
