import { hashPassword, id } from "./crypto-utils";
import { DEMO_ESTABLISHMENT_ID, DEMO_ESTABLISHMENT_SLUG } from "./demo";
import type { Command, MesaFlowStore, Order, OrderItem, OrderStatus, Product } from "./types";

const EST_ID = DEMO_ESTABLISHMENT_ID;
const DEMO_SLUG = DEMO_ESTABLISHMENT_SLUG;

const img = (seed: string) =>
  `https://images.unsplash.com/photo-${seed}?w=800&q=80&auto=format&fit=crop`;

export function buildDemoStore(): MesaFlowStore {
  const now = new Date().toISOString();
  const sectors = {
    sec_cozinha: {
      id: "sec_cozinha",
      establishmentId: EST_ID,
      name: "Cozinha",
      kind: "COZINHA" as const,
      color: "#f97316",
      active: true,
    },
    sec_balcao: {
      id: "sec_balcao",
      establishmentId: EST_ID,
      name: "Balcão",
      kind: "BALCAO" as const,
      color: "#3b82f6",
      active: true,
    },
    sec_bar: {
      id: "sec_bar",
      establishmentId: EST_ID,
      name: "Bar",
      kind: "BAR" as const,
      color: "#a855f7",
      active: true,
    },
  };

  const categories = {
    cat_burger: { id: "cat_burger", establishmentId: EST_ID, name: "Hambúrgueres", emoji: "🍔", sortOrder: 1, active: true },
    cat_pizza: { id: "cat_pizza", establishmentId: EST_ID, name: "Pizzas", emoji: "🍕", sortOrder: 2, active: true },
    cat_porcao: { id: "cat_porcao", establishmentId: EST_ID, name: "Porções", emoji: "🍟", sortOrder: 3, active: true },
    cat_bebida: { id: "cat_bebida", establishmentId: EST_ID, name: "Bebidas", emoji: "🥤", sortOrder: 4, active: true },
    cat_doce: { id: "cat_doce", establishmentId: EST_ID, name: "Sobremesas", emoji: "🍰", sortOrder: 5, active: true },
    cat_rodizio: { id: "cat_rodizio", establishmentId: EST_ID, name: "Rodízio", emoji: "🔥", sortOrder: 6, active: true },
  };

  const products: Record<string, Product> = {
    p_xburger: {
      id: "p_xburger",
      establishmentId: EST_ID,
      categoryId: "cat_burger",
      sectorId: "sec_cozinha",
      name: "X-Burger Artesanal",
      description: "Blend 180g, queijo prato, molho da casa e pão brioche.",
      price: 32.9,
      image: img("1568901716194-d49b35ccf59f"),
      tags: ["destaque"],
      prepMinutes: 18,
      availability: "AMBOS",
      featured: true,
      active: true,
      variants: [
        { id: "v_simples", name: "Simples", priceDelta: 0 },
        { id: "v_duplo", name: "Duplo", priceDelta: 14 },
      ],
      addons: [
        { id: "a_bacon", name: "Bacon", price: 6 },
        { id: "a_cheddar", name: "Cheddar", price: 5 },
      ],
      rodizioIncluded: false,
    },
    p_xsalada: {
      id: "p_xsalada",
      establishmentId: EST_ID,
      categoryId: "cat_burger",
      sectorId: "sec_cozinha",
      name: "X-Salada Premium",
      description: "Hambúrguer com salada fresca, tomate e cebola roxa.",
      price: 36.9,
      image: img("1550547660-b9eea9836a88"),
      tags: [],
      prepMinutes: 20,
      availability: "AMBOS",
      featured: false,
      active: true,
      variants: [],
      addons: [{ id: "a_ovo", name: "Ovo", price: 4 }],
      rodizioIncluded: false,
    },
    p_pizza_calabresa: {
      id: "p_pizza_calabresa",
      establishmentId: EST_ID,
      categoryId: "cat_pizza",
      sectorId: "sec_cozinha",
      name: "Pizza Calabresa",
      description: "Massa fina, calabresa fatiada e cebola.",
      price: 54.9,
      image: img("1513104890138-7c749659a591"),
      tags: ["rodízio"],
      prepMinutes: 25,
      availability: "AMBOS",
      featured: true,
      active: true,
      variants: [
        { id: "v_p", name: "Broto", priceDelta: -12 },
        { id: "v_g", name: "Grande", priceDelta: 18 },
      ],
      addons: [{ id: "a_borda_cat", name: "Borda catupiry", price: 12 }],
      rodizioIncluded: true,
    },
    p_pizza_frango: {
      id: "p_pizza_frango",
      establishmentId: EST_ID,
      categoryId: "cat_pizza",
      sectorId: "sec_cozinha",
      name: "Frango com Catupiry",
      description: "Clássica da casa com frango desfiado.",
      price: 56.9,
      image: img("1574071318508-1cdbab1a896f"),
      tags: ["rodízio"],
      prepMinutes: 25,
      availability: "AMBOS",
      featured: false,
      active: true,
      variants: [],
      addons: [],
      rodizioIncluded: true,
      rodizioPremiumPrice: 9.9,
    },
    p_pizza_marg: {
      id: "p_pizza_marg",
      establishmentId: EST_ID,
      categoryId: "cat_pizza",
      sectorId: "sec_cozinha",
      name: "Marguerita",
      description: "Molho de tomate, mussarela e manjericão.",
      price: 49.9,
      image: img("1604382354936-07c5d9983bd3"),
      tags: ["rodízio"],
      prepMinutes: 22,
      availability: "AMBOS",
      featured: false,
      active: true,
      variants: [],
      addons: [],
      rodizioIncluded: true,
    },
    p_batata: {
      id: "p_batata",
      establishmentId: EST_ID,
      categoryId: "cat_porcao",
      sectorId: "sec_cozinha",
      name: "Batata Frita Grande",
      description: "Porção generosa com alecrim e parmesão.",
      price: 28.9,
      image: img("1573080496219-a418b8a838f6"),
      tags: [],
      prepMinutes: 12,
      availability: "VITRINE",
      featured: false,
      active: true,
      variants: [],
      addons: [{ id: "a_cheddar_bat", name: "Cheddar", price: 8 }],
      rodizioIncluded: false,
    },
    p_coxinha: {
      id: "p_coxinha",
      establishmentId: EST_ID,
      categoryId: "cat_porcao",
      sectorId: "sec_balcao",
      name: "Coxinha de Frango",
      description: "Massa crocante, recheio cremoso (unidade).",
      price: 9.9,
      image: img("1608037375126-370c4aa7859e"),
      tags: [],
      prepMinutes: 5,
      availability: "VITRINE",
      featured: false,
      active: true,
      variants: [],
      addons: [],
      rodizioIncluded: false,
    },
    p_coca: {
      id: "p_coca",
      establishmentId: EST_ID,
      categoryId: "cat_bebida",
      sectorId: "sec_balcao",
      name: "Coca-Cola Lata",
      description: "350ml gelada.",
      price: 8.9,
      image: img("1629203851122-3726ecdf080e"),
      tags: [],
      prepMinutes: 1,
      availability: "VITRINE",
      featured: false,
      active: true,
      variants: [],
      addons: [],
      rodizioIncluded: false,
    },
    p_cappuccino: {
      id: "p_cappuccino",
      establishmentId: EST_ID,
      categoryId: "cat_bebida",
      sectorId: "sec_balcao",
      name: "Cappuccino",
      description: "Espresso, leite vaporizado e espuma.",
      price: 14.9,
      image: img("1572442383536-47c21b6ff7c5"),
      tags: [],
      prepMinutes: 6,
      availability: "SOB_DEMANDA",
      featured: true,
      active: true,
      variants: [
        { id: "v_p", name: "Pequeno", priceDelta: 0 },
        { id: "v_g", name: "Grande", priceDelta: 4 },
      ],
      addons: [
        { id: "a_leite_amend", name: "Leite de amêndoas", price: 3 },
        { id: "a_chantilly", name: "Chantilly", price: 2 },
      ],
      rodizioIncluded: false,
    },
    p_chopp: {
      id: "p_chopp",
      establishmentId: EST_ID,
      categoryId: "cat_bebida",
      sectorId: "sec_bar",
      name: "Chopp Artesanal",
      description: "300ml da torneira.",
      price: 16.9,
      image: img("1608272941294-597ded4a8af3"),
      tags: [],
      prepMinutes: 2,
      availability: "VITRINE",
      featured: false,
      active: true,
      variants: [{ id: "v_500", name: "500ml", priceDelta: 8 }],
      addons: [],
      rodizioIncluded: false,
    },
    p_caipirinha: {
      id: "p_caipirinha",
      establishmentId: EST_ID,
      categoryId: "cat_bebida",
      sectorId: "sec_bar",
      name: "Caipirinha",
      description: "Limão, cachaça e gelo.",
      price: 22.9,
      image: img("1551539166-88256b0655f4"),
      tags: [],
      prepMinutes: 5,
      availability: "SOB_DEMANDA",
      featured: false,
      active: true,
      variants: [],
      addons: [],
      rodizioIncluded: false,
    },
    p_pudim: {
      id: "p_pudim",
      establishmentId: EST_ID,
      categoryId: "cat_doce",
      sectorId: "sec_balcao",
      name: "Pudim de Leite",
      description: "Receita da vó, calda caramelizada.",
      price: 18.9,
      image: img("1586985289765-7b0e9e725bfe"),
      tags: [],
      prepMinutes: 3,
      availability: "VITRINE",
      featured: true,
      active: true,
      variants: [],
      addons: [],
      rodizioIncluded: false,
    },
    p_brownie: {
      id: "p_brownie",
      establishmentId: EST_ID,
      categoryId: "cat_doce",
      sectorId: "sec_balcao",
      name: "Brownie com Sorvete",
      description: "Chocolate belga e sorvete de creme.",
      price: 24.9,
      image: img("1606313564204-75a0c8d0538f"),
      tags: [],
      prepMinutes: 5,
      availability: "SOB_DEMANDA",
      featured: false,
      active: true,
      variants: [],
      addons: [],
      rodizioIncluded: false,
    },
    p_pizza_pepper: {
      id: "p_pizza_pepper",
      establishmentId: EST_ID,
      categoryId: "cat_rodizio",
      sectorId: "sec_cozinha",
      name: "Pizza Pepperoni",
      description: "Pepperoni importado e mussarela.",
      price: 59.9,
      image: img("1628840040245-3fea7438c6a0"),
      tags: ["rodízio", "premium"],
      prepMinutes: 25,
      availability: "AMBOS",
      featured: true,
      active: true,
      variants: [],
      addons: [],
      rodizioIncluded: true,
      rodizioPremiumPrice: 9.9,
    },
    p_salada: {
      id: "p_salada",
      establishmentId: EST_ID,
      categoryId: "cat_porcao",
      sectorId: "sec_cozinha",
      name: "Salada da Casa",
      description: "Mix de folhas, tomate cereja e molho balsâmico.",
      price: 26.9,
      image: img("1512621776951-a57141f2eefd"),
      tags: [],
      prepMinutes: 8,
      availability: "AMBOS",
      featured: false,
      active: true,
      variants: [],
      addons: [],
      rodizioIncluded: false,
    },
  };

  const tables: MesaFlowStore["tables"] = {};
  for (let i = 1; i <= 10; i++) {
    const tid = `tbl_${i}`;
    tables[tid] = {
      id: tid,
      establishmentId: EST_ID,
      number: String(i).padStart(2, "0"),
      name: `Mesa ${String(i).padStart(2, "0")}`,
      capacity: i <= 4 ? 4 : i <= 7 ? 6 : 8,
      status: i === 4 || i === 8 ? "OCUPADA" : i === 3 ? "AGUARDANDO_PAGAMENTO" : "LIVRE",
      qrToken: `mesa-${i}`,
    };
  }

  const cmd4: Command = {
    id: "cmd_demo_4",
    establishmentId: EST_ID,
    tableId: "tbl_4",
    openedAt: new Date(Date.now() - 45 * 60000).toISOString(),
    status: "ABERTA",
    guestCount: 4,
    total: 0,
  };
  tables.tbl_4.commandId = cmd4.id;

  const cmd8: Command = {
    id: "cmd_demo_8",
    establishmentId: EST_ID,
    tableId: "tbl_8",
    openedAt: new Date(Date.now() - 20 * 60000).toISOString(),
    status: "ABERTA",
    guestCount: 2,
    total: 0,
  };
  tables.tbl_8.commandId = cmd8.id;

  function demoItem(
    productId: string,
    qty: number,
    status: OrderStatus = "EM_PREPARO",
    notes?: string,
  ): OrderItem {
    const p = products[productId as keyof typeof products];
    const sec = sectors[p.sectorId as keyof typeof sectors];
    return {
      id: id("oi_"),
      productId: p.id,
      productName: p.name,
      sectorId: p.sectorId,
      sectorName: sec.name,
      qty,
      unitPrice: p.price,
      variantDelta: 0,
      addons: [],
      notes,
      status,
    };
  }

  const demoOrders: Order[] = [
    {
      id: "ord_demo_1",
      establishmentId: EST_ID,
      tableId: "tbl_8",
      tableNumber: "08",
      commandId: cmd8.id,
      number: 1294,
      status: "EM_PREPARO",
      items: [demoItem("p_xburger", 2, "EM_PREPARO", "1 sem cebola"), demoItem("p_batata", 1)],
      total: 94.7,
      source: "MESA",
      createdAt: new Date(Date.now() - 4 * 60000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "ord_demo_2",
      establishmentId: EST_ID,
      tableId: "tbl_4",
      tableNumber: "04",
      commandId: cmd4.id,
      number: 1293,
      status: "NOVO",
      items: [demoItem("p_cappuccino", 2), demoItem("p_coxinha", 1)],
      total: 39.7,
      source: "MESA",
      createdAt: new Date(Date.now() - 1 * 60000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "ord_demo_3",
      establishmentId: EST_ID,
      tableId: "tbl_4",
      tableNumber: "04",
      commandId: cmd4.id,
      number: 1290,
      status: "PRONTO",
      items: [demoItem("p_chopp", 2), demoItem("p_caipirinha", 1)],
      total: 56.7,
      source: "MESA",
      createdAt: new Date(Date.now() - 18 * 60000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "ord_demo_4",
      establishmentId: EST_ID,
      tableId: "tbl_4",
      tableNumber: "04",
      commandId: cmd4.id,
      number: 1288,
      status: "ENTREGUE",
      items: [demoItem("p_pizza_calabresa", 1), demoItem("p_salada", 1)],
      total: 81.8,
      source: "MESA",
      createdAt: new Date(Date.now() - 55 * 60000).toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  cmd4.total = demoOrders.filter((o) => o.commandId === cmd4.id).reduce((s, o) => s + o.total, 0);
  cmd8.total = demoOrders.filter((o) => o.commandId === cmd8.id).reduce((s, o) => s + o.total, 0);

  return {
    establishments: {
      [EST_ID]: {
        id: EST_ID,
        slug: DEMO_SLUG,
        name: "Ponto do Sabor",
        tagline: "Garçom digital na sua mesa",
        logo: "🍽️",
        open: true,
        rodizioEnabled: true,
        settings: {
          currency: "BRL",
          allowEditAfterPrep: false,
          soundNotifications: true,
          minIntervalRodizioSec: 120,
        },
        createdAt: now,
      },
    },
    users: {
      user_owner: {
        id: "user_owner",
        establishmentId: EST_ID,
        email: "owner@pontodosabor.com",
        passwordHash: hashPassword("demo123"),
        name: "Carlos Mendes",
        role: "OWNER",
        active: true,
      },
    },
    sectors,
    categories,
    products,
    tables,
    commands: { [cmd4.id]: cmd4, [cmd8.id]: cmd8 },
    orders: Object.fromEntries(demoOrders.map((o) => [o.id, o])),
    rodizios: {
      rod_pizza: {
        id: "rod_pizza",
        establishmentId: EST_ID,
        name: "Rodízio de Pizza",
        pricePerPerson: 59.9,
        durationMinutes: 90,
        maxItemsPerRound: 6,
        maxRounds: 8,
        minIntervalSec: 120,
        drinksIncluded: false,
        active: true,
        productIds: ["p_pizza_calabresa", "p_pizza_frango", "p_pizza_marg", "p_pizza_pepper"],
        premiumProductIds: ["p_pizza_frango", "p_pizza_pepper"],
      },
    },
    rodizioRounds: {},
    notifications: {},
    orderCounter: { [EST_ID]: 1294 },
  };
}

